# Generated by Django 3.1.1 on 2020-09-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_address', models.CharField(max_length=300)),
                ('encrypted_content', models.CharField(max_length=5000)),
            ],
        ),
    ]
