# Generated by Django 3.1.1 on 2020-09-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcontent',
            name='encrypted_content',
            field=models.TextField(),
        ),
    ]
